extends RefCounted
const DUNGEONS={
	"forest":{"name":"꽃바람 숲","level":1,"theme":0,"boss":"warden","elite":"goblin_captain","mobs":["shade","imp","fairy","rat","goblin_archer"],"description":"꽃길과 굽은 오솔길 · 슬라임·고블린·벌과 고블린 대장"},
	"cave":{"name":"푸른 수정 동굴","level":5,"theme":1,"boss":"golem","elite":"orc_champion","mobs":["beetle","bat","mole","ember_slime","cave_bat","spider"],"description":"넓은 채굴장과 좁은 연결로 · 곤충·야수·오크와 동굴 투사"},
	"ruins":{"name":"햇무리 유적","level":10,"theme":2,"boss":"sentinel","elite":"centurion","mobs":["clockwork","spellbook","fox","frost_slime","goblin_shaman","orc_axeman","skeleton"],"description":"격자 회랑과 추가 지름길 · 기계·야수·언데드와 백인대장"}}
const ENEMIES={
	"shade": {
		"name": "풀빛 슬라임",
		"health": 70,
		"damage": 10,
		"speed": 1.25,
		"range": 1.0,
		"xp": 25,
		"gold": 6,
		"respawn": 45,
		"ai": "melee",
		"art": 0,
		"height": 62,
		"art_sheet": "enemies"
	},
	"imp": {
		"name": "숲 고블린",
		"health": 80,
		"damage": 14,
		"speed": 1.1,
		"range": 1.25,
		"xp": 32,
		"gold": 8,
		"respawn": 50,
		"ai": "melee",
		"art": 1,
		"height": 86,
		"art_sheet": "enemies"
	},
	"fairy": {
		"name": "독침 벌",
		"health": 65,
		"damage": 10,
		"speed": 1.8,
		"range": 3.5,
		"xp": 40,
		"gold": 10,
		"respawn": 60,
		"ai": "ranged",
		"art": 2,
		"height": 72,
		"art_sheet": "enemies"
	},
	"warden": {
		"name": "꽃숲의 파수목",
		"health": 800,
		"damage": 30,
		"speed": 0.9,
		"range": 2.2,
		"xp": 220,
		"gold": 90,
		"respawn": 180,
		"ai": "boss",
		"art": 3
	},
	"beetle": {
		"name": "바위 딱정벌레",
		"health": 180,
		"damage": 20,
		"speed": 1.1,
		"range": 1.2,
		"xp": 60,
		"gold": 12,
		"respawn": 60,
		"ai": "armored",
		"art": 3,
		"height": 78,
		"art_sheet": "enemies"
	},
	"bat": {
		"name": "바위 멧돼지",
		"health": 115,
		"damage": 16,
		"speed": 2.5,
		"range": 3.0,
		"xp": 50,
		"gold": 10,
		"respawn": 50,
		"ai": "charger",
		"art": 4,
		"height": 84,
		"art_sheet": "enemies"
	},
	"mole": {
		"name": "동굴 오크",
		"health": 160,
		"damage": 24,
		"speed": 1.4,
		"range": 1.8,
		"xp": 65,
		"gold": 16,
		"respawn": 60,
		"ai": "melee",
		"art": 5,
		"height": 110,
		"art_sheet": "enemies"
	},
	"golem": {
		"name": "푸른 심장 골렘",
		"health": 1600,
		"damage": 45,
		"speed": 0.8,
		"range": 2.7,
		"xp": 500,
		"gold": 180,
		"respawn": 240,
		"ai": "boss",
		"art": 7
	},
	"clockwork": {
		"name": "태엽 경비병",
		"health": 250,
		"damage": 26,
		"speed": 1.6,
		"range": 2.0,
		"xp": 90,
		"gold": 22,
		"respawn": 65,
		"ai": "armored",
		"art": 6,
		"height": 96,
		"art_sheet": "enemies"
	},
	"spellbook": {
		"name": "정찰 드론",
		"health": 185,
		"damage": 30,
		"speed": 1.3,
		"range": 4.5,
		"xp": 100,
		"gold": 25,
		"respawn": 70,
		"ai": "ranged",
		"art": 7,
		"height": 76,
		"art_sheet": "enemies"
	},
	"fox": {
		"name": "황토 늑대",
		"health": 210,
		"damage": 24,
		"speed": 2.6,
		"range": 2.2,
		"xp": 90,
		"gold": 20,
		"respawn": 55,
		"ai": "charger",
		"art": 8,
		"height": 86,
		"art_sheet": "enemies"
	},
	"sentinel": {
		"name": "햇무리 수호기사",
		"health": 2400,
		"damage": 55,
		"speed": 1.1,
		"range": 2.5,
		"xp": 800,
		"gold": 300,
		"respawn": 300,
		"ai": "boss",
		"art": 11
	},
	"ember_slime": {
		"name": "잿불 슬라임",
		"health": 130,
		"damage": 17,
		"speed": 1.05,
		"range": 2.0,
		"xp": 52,
		"gold": 11,
		"respawn": 60,
		"ai": "melee",
		"art": 0,
		"art_sheet": "reinforcements",
		"height": 65,
		"elite": false
	},
	"frost_slime": {
		"name": "서리 슬라임",
		"health": 210,
		"damage": 23,
		"speed": 1.0,
		"range": 3.5,
		"xp": 87,
		"gold": 20,
		"respawn": 60,
		"ai": "ranged",
		"art": 1,
		"art_sheet": "reinforcements",
		"height": 65,
		"elite": false
	},
	"cave_bat": {
		"name": "동굴 박쥐",
		"health": 105,
		"damage": 15,
		"speed": 2.6,
		"range": 2.4,
		"xp": 45,
		"gold": 9,
		"respawn": 60,
		"ai": "charger",
		"art": 2,
		"art_sheet": "reinforcements",
		"height": 70,
		"elite": false
	},
	"rat": {
		"name": "들쥐",
		"health": 55,
		"damage": 8,
		"speed": 2.25,
		"range": 1.1,
		"xp": 20,
		"gold": 5,
		"respawn": 60,
		"ai": "melee",
		"art": 3,
		"art_sheet": "reinforcements",
		"height": 55,
		"elite": false
	},
	"spider": {
		"name": "동굴 거미",
		"health": 135,
		"damage": 19,
		"speed": 1.65,
		"range": 3.2,
		"xp": 58,
		"gold": 13,
		"respawn": 60,
		"ai": "ranged",
		"art": 4,
		"art_sheet": "reinforcements",
		"height": 72,
		"elite": false
	},
	"goblin_archer": {
		"name": "고블린 궁수",
		"health": 65,
		"damage": 12,
		"speed": 1.6,
		"range": 4.2,
		"xp": 35,
		"gold": 9,
		"respawn": 60,
		"ai": "ranged",
		"art": 5,
		"art_sheet": "reinforcements",
		"height": 86,
		"elite": false
	},
	"goblin_shaman": {
		"name": "고블린 주술사",
		"health": 195,
		"damage": 24,
		"speed": 1.3,
		"range": 3.8,
		"xp": 105,
		"gold": 28,
		"respawn": 60,
		"ai": "healer",
		"art": 6,
		"art_sheet": "reinforcements",
		"height": 90,
		"elite": false
	},
	"orc_axeman": {
		"name": "오크 도끼병",
		"health": 290,
		"damage": 35,
		"speed": 1.35,
		"range": 2.0,
		"xp": 120,
		"gold": 30,
		"respawn": 60,
		"ai": "melee",
		"art": 7,
		"art_sheet": "reinforcements",
		"height": 115,
		"elite": false
	},
	"skeleton": {
		"name": "해골 병사",
		"health": 225,
		"damage": 25,
		"speed": 1.45,
		"range": 1.7,
		"xp": 95,
		"gold": 22,
		"respawn": 60,
		"ai": "armored",
		"art": 8,
		"art_sheet": "reinforcements",
		"height": 92,
		"elite": false
	},
	"goblin_captain": {
		"name": "고블린 대장",
		"health": 390,
		"damage": 23,
		"speed": 1.55,
		"range": 2.2,
		"xp": 120,
		"gold": 55,
		"respawn": 120,
		"ai": "melee",
		"art": 9,
		"art_sheet": "reinforcements",
		"height": 160,
		"elite": true
	},
	"orc_champion": {
		"name": "오크 투사",
		"health": 850,
		"damage": 38,
		"speed": 1.25,
		"range": 2.5,
		"xp": 270,
		"gold": 100,
		"respawn": 120,
		"ai": "armored",
		"art": 10,
		"art_sheet": "reinforcements",
		"height": 180,
		"elite": true
	},
	"centurion": {
		"name": "기계 백인대장",
		"health": 1350,
		"damage": 45,
		"speed": 1.3,
		"range": 3.6,
		"xp": 420,
		"gold": 170,
		"respawn": 120,
		"ai": "armored",
		"art": 11,
		"art_sheet": "reinforcements",
		"height": 175,
		"elite": true
	}
}
const FACILITIES={
	"smith":{"name":"대장간","pos":Vector2(11,17),"art":0,"height":430.0},
	"shop":{"name":"별씨앗 상점","pos":Vector2(18,12),"art":1,"height":430.0},
	"alchemy":{"name":"연금술 공방","pos":Vector2(27,17),"art":2,"height":460.0},
	"guild":{"name":"모험가 길드","pos":Vector2(9,27),"art":3,"height":500.0},
	"inn":{"name":"초승달 여관","pos":Vector2(21,31),"art":4,"height":470.0},
	"portal":{"name":"원정의 문","pos":Vector2(25,37),"art":5,"height":260.0},
	"costume":{"name":"별실 부티크","pos":Vector2(9,8),"art":1,"height":400.0},
	"training":{"name":"모험가 수련장","pos":Vector2(34,33),"art":5,"height":0.0,"footprint":false}}
const RESIDENTS={
	"smith":{"name":"대장장이 루아","avatar":"gat_blade_combat","greeting":"날이 무뎌졌나요? 광석을 가져오면 단단하게 벼려드릴게요."},
	"shop":{"name":"상인 밀리","avatar":"gat_addition_04_1","greeting":"여행에 필요한 물건이라면 여기 있어요. 안 쓰는 장비도 받아요!"},
	"alchemy":{"name":"연금술사 로제","avatar":"gat_role_healer_2","greeting":"별씨앗 한 줌에는 뜻밖의 힘이 숨어 있답니다."},
	"guild":{"name":"길드 안내원 세온","avatar":"gat_addition_11_1","greeting":"모험가님, 토벌 의뢰를 확인해 보세요. 무사히 돌아오길 바라요."},
	"inn":{"name":"여관지기 아멜","avatar":"gat_addition_01_2","greeting":"어서 오세요. 따뜻한 식사와 포근한 침대가 준비됐어요."},
	"costume":{"name":"재단사 세라","avatar":"gat_addition_04_2","greeting":"모험가님에게 어울리는 옷을 골라 보세요."},
	"training":{"name":"수련 교관 레나","avatar":"gat_role_tank_1","greeting":"허수아비를 상대로 새 기술을 시험해 보세요. 수련 기록은 제가 정리해 드릴게요."}}
static func resident_pos(key:String)->Vector2:return FACILITIES[key].pos+Vector2(1.25,.35)
static func nearest(pos:Vector2)->String:
	var best="";var distance=2.7
	for key in FACILITIES:
		var d=pos.distance_to(FACILITIES[key].pos)
		if RESIDENTS.has(key):d=minf(d,pos.distance_to(resident_pos(key)))
		if d<distance:distance=d;best=key
	return best
static func display_height(kind:String)->float:
	var c=ENEMIES[kind]
	if c.ai=="boss":return 335.
	if c.get("elite",false):return float(c.get("height",160))*1.12
	# Preserve silhouettes: low creatures have broad bodies; humanoids stand near hero height.
	return maxf(92.,float(c.get("height",86))*1.3)
