extends SceneTree
## Exercises real skill dispatch before checking the visual event consumer.
const Simulation = preload("res://scripts/simulation.gd")
const Content = preload("res://scripts/content.gd")
const Scaling = preload("res://scripts/skill_scaling.gd")
const Catalog = preload("res://scripts/skill_vfx_catalog.gd")
const FAMILIES = ["slash", "spin", "fire", "frost", "thunder", "impact", "rain", "shot", "poison", "heal", "barrier", "haste", "summon", "cards", "chain", "vortex", "blink", "rune"]
const MOVEMENT = ["dash", "rush", "retreat", "weave", "flank", "blink", "teleport", "teleport_chain", "ally_dash", "heavy_dash", "card_retreat", "chain_dash"]
var checks = 0
var failures: Array = []
var samples: Array = []
var families: Dictionary = {}
var casts = 0
var movement_casts = 0

func _initialize():
	run.call_deferred()

func check(ok: bool, label: String):
	checks += 1
	if not ok:
		failures.append(label)
		push_error(label)

func advance(sim, p: Dictionary, seconds: float):
	# As in jobs.gd, tick the combat systems without introducing enemy AI
	# interruptions into a visual event test.
	for _step in range(ceili(seconds / .05)):
		sim.combat.tick_player(p, .05)
		sim.combat.tick_projectiles(.05)
		sim.combat.skills.tick(.05)

func find_active(cls: String, mode: String) -> Dictionary:
	for node in Content.SKILLS[cls]:
		if node.effect == "active" and node.get("mode", "") == mode:
			return node
	return {}

func prepare_requirements(sim, p: Dictionary, node: Dictionary):
	var mode = str(node.get("mode", ""))
	# Starting rank/loadout are a learned-character fixture. Runtime resources
	# are generated by the same combat actions that produce them in play.
	if int(node.get("rune_cost", 0)) > 0 or mode in ["teleport", "teleport_chain"]:
		for _hit in range(maxi(1, int(node.get("rune_cost", 0)))):
			check(sim.action(p.id, "attack"), "resource-generating basic attack " + node.id)
			sim.tick(.65)
	if p.class_id == "hunter":
		advance(sim, p, .05)
	if mode.begins_with("pet_") and p.class_id == "summoner":
		var summon = find_active(p.class_id, "summon")
		check(not summon.is_empty(), "summoner has a summon prerequisite")
		if not summon.is_empty():
			p.skill_ranks[summon.id] = 1
			p.skill_loadout.skill_f = summon.id
			check(sim.action(p.id, "skill_f"), "summon prerequisite " + node.id)
			advance(sim, p, 1.)
	if mode in ["reroll", "dice_buff"]:
		var dice = find_active(p.class_id, "dice")
		check(not dice.is_empty(), "gambler has a dice prerequisite")
		if not dice.is_empty():
			p.skill_ranks[dice.id] = 1
			p.skill_loadout.skill_f = dice.id
			check(sim.action(p.id, "skill_f"), "dice prerequisite " + node.id)
			advance(sim, p, 1.)

func inspect_cast(sim, cls: String, node: Dictionary, rank: int):
	sim.players.clear()
	sim.enemies.clear()
	sim.events.clear()
	sim.combat.projectiles.clear()
	sim.combat.skills.zones.clear()
	var p = sim.add_player(1, "이펙트 검사", {"schema_version": 6, "level": 100, "class_id": cls, "skill_ranks": {node.id: rank}, "skill_loadout": {"skill_q": node.id}})
	p.pos = Vector2(sim.map.rooms[1])
	p.aim = Vector2.RIGHT
	p.hp = maxi(1, int(p.max_hp * .25))
	for index in range(5):
		var at = sim.combat.skills.target(p, 1. + index * .4)
		var enemy = sim.spawn_enemy("shade", at, 1)
		enemy.hp = 1000000
		enemy.max_hp = 1000000
	prepare_requirements(sim, p, node)
	sim.events.clear()
	var origin: Vector2 = p.pos
	var mode = str(node.get("mode", "")) if Content.job(p) else str(Scaling.profile(node, rank).mode)
	var label = "%s rank %d" % [node.id, rank]
	check(sim.action(p.id, "skill_q"), "cast " + label)
	casts += 1
	advance(sim, p, maxf(3., float(node.get("windup", 0)) + .5))
	var matching: Array = []
	for event in sim.events:
		if event.get("type", "") == "skill_fx" and event.get("skill_id", "") == node.id:
			matching.append(event)
	check(not matching.is_empty(), "active produces attributed visual event " + label)
	for event in matching:
		check(event.get("class_id", "") == cls and event.get("skill_mode", "") == mode, "class and mode survive " + label)
		check(int(event.get("rank", 0)) == rank, "rank survives " + label)
		check(event.get("owner", -1) == p.id, "owner survives " + label)
		var duration = float(event.get("duration", 0))
		check(is_finite(duration) and duration > 0 and duration < 60, "bounded effect duration " + label)
		var radius = float(event.get("radius", -1))
		check(is_finite(radius) and radius >= 0 and radius < 100, "finite radius " + label)
		for key in ["pos", "origin", "end", "dir"]:
			check(event.get(key) is Vector2 and event.get(key, Vector2.INF).is_finite(), "finite " + key + " " + label)
		var before: Dictionary = event.duplicate(true)
		var profile = Catalog.profile(event)
		check(event == before, "visual classification preserves source event " + label)
		check(profile.get("family", "") in FAMILIES, "classified active " + label)
		check(profile.get("color") is Color and profile.get("accent") is Color, "valid palette " + label)
		families[profile.get("family", "")] = true
		samples.append(event.duplicate(true))
	if mode in MOVEMENT and not p.pos.is_equal_approx(origin):
		movement_casts += 1
		check(matching.any(func(event): return event.get("origin", Vector2.INF).is_equal_approx(origin) and event.get("end", Vector2.INF).is_equal_approx(p.pos)), "movement path matches actual player displacement " + label)
	check(not p.has("casting_vfx") and not p.has("casting_rank"), "cast context does not leak " + label)

func verify_consumer():
	var game = load("res://main.tscn").instantiate()
	game.options.mute = true
	game.options["save-dir"] = ProjectSettings.globalize_path("res://../runtime/vfx-check-saves/" + str(Time.get_ticks_usec()))
	root.add_child(game)
	game.set_process(false)
	game.set_physics_process(false)
	game.session.set_physics_process(false)
	await process_frame
	var nodes_before = int(Performance.get_monitor(Performance.OBJECT_NODE_COUNT))
	var duration = 0.
	for source in samples:
		var incoming: Dictionary = source.duplicate(true)
		game.on_event(incoming)
		var retained: Dictionary = game.effects.back()
		for key in ["skill_id", "skill_mode", "class_id", "rank", "origin", "end", "pos", "dir", "owner"]:
			check(retained.get(key) == source.get(key), "event consumer preserves " + key)
		check(is_equal_approx(retained.life, source.duration) and is_equal_approx(retained.max_life, source.duration), "consumer applies finite lifetime")
		duration = maxf(duration, source.duration)
	check(game.effects.size() == samples.size(), "simultaneous events reach consumer")
	game._process(.01)
	check(not game.effects.is_empty(), "live effects survive initial frame")
	game._process(duration + .1)
	check(game.effects.is_empty(), "all simultaneous effects expire")
	# Repeat to expose accumulation across bursts rather than only one clear.
	for _burst in range(5):
		for index in range(mini(samples.size(), 100)):
			game.on_event(samples[index].duplicate(true))
		game._process(duration + .1)
	check(game.effects.is_empty(), "repeated bursts leave no effect entries")
	check(int(Performance.get_monitor(Performance.OBJECT_NODE_COUNT)) == nodes_before, "effect bursts do not allocate nodes")
	game.stop_audio()
	# Audio playback is released on the audio thread. Match visual_jobs.gd's
	# shutdown grace period so a title-music WAV is not retained at process exit.
	await create_timer(.5).timeout
	game.queue_free()
	game = null
	await process_frame
	await process_frame

func run():
	Content.initialize_jobs()
	var sim = Simulation.new(123)
	var active_count = 0
	for cls in Content.SKILLS:
		for node in Content.SKILLS[cls]:
			if node.effect != "active":
				continue
			active_count += 1
			for rank in [1, Content.max_rank(node)]:
				inspect_cast(sim, cls, node, rank)
	check(casts == active_count * 2 and active_count >= 200, "all basic and advanced actives checked at first and maximum ranks")
	check(movement_casts >= 10, "real movement skills exercised")
	for family in FAMILIES:
		check(families.has(family), "real skill coverage for " + family)
		check(Catalog.profile({"vfx": family, "fx": "unmapped"}).family == family, "gallery explicit override " + family)
	# Release the simulation before suspending for the scene consumer. Otherwise
	# the coroutine can retain its runtime graph through engine shutdown.
	sim = null
	await verify_consumer()
	print("SKILL_VFX_TESTS checks=", checks, " failures=", failures.size(), " casts=", casts, " families=", families.size(), " events=", samples.size(), " movement=", movement_casts)
	quit(0 if failures.is_empty() else 1)
